// GPX race routes configuration
const raceRoutes = [
    {
        id: "lommedalen-rundt",
        name: "Lommedalen Rundt",
        files: ["race-calendar/lommedalen-rundt/lommedalen-rundt-2025-published.gpx"],
        gpxUpdated: '2026-06-08',
        color: "#8338ec",
        url: "https://www.lommedalenrundt.no/omlr",
        description: "Lommedalen Rundt er et løp på åsene rundt Lommedalen i Bærum, arrangert første gang i 2015.",
        useCalculatedStats: true,
        manualDistance: 160,
        category: "100-miles",
        date: "2026-10-24"
    },
    {
        id: 'nsm-ultra-2025',
        name: 'NSM Ultra 2025',
        files: ['race-calendar/NordmarkaSkogsmaraton/NSM_Ultra_2025.gpx'],
        gpxUpdated: '2026-01-30',
        color: '#ff6b35',
        url: 'https://nordmarkaskogsmaraton.no/',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-06-20'
    },
    {
        id: 'obt-oslo-bergen-trail',
        name: 'OBT Oslo-Bergen Trail',
        files: [
            'race-calendar/OsloBergenTrail/M1_Oslo-Bergen.gpx',
            'race-calendar/OsloBergenTrail/M2_Vasstulan-Bergen.gpx',
            'race-calendar/OsloBergenTrail/M3_Voss-Bergen.gpx',
            'race-calendar/OsloBergenTrail/M4_Gullbotn-Bergen.gpx'
        ],
        gpxUpdated: '2026-01-30',
        color: '#3498db',
        url: 'https://oslobergentrail.com/',
        manualDistance: 500,
        manualElevation: 15000,
        category: '100-miles-plus',
        date: '2027-07-01'
    },
    {
        id: 'smve-soria-moria-til-verdens-ende',
        name: 'SMVE - Soria Moria til Verdens Ende',
        files: ['race-calendar/SoriaMoriaTilVerdensEnde/SMVE_2024_100_miles_02.gpx'],
        gpxUpdated: '2026-01-30',
        color: '#9b59b6',
        url: 'https://soriamoriatilverdensende.com',
        useCalculatedStats: true,
        category: '100-miles',
        date: '2026-05-30',
    },
    {
        id: 'noesen-hundreds',
        name: 'Nøsen Hundreds',
        files: ['race-calendar/Nøsen/Nosen_100.gpx'],
        gpxUpdated: '2026-01-30',
        color: '#e74c3c',
        url: 'https://www.nosenhundreds.com/',
        useCalculatedStats: true,
        category: '100k',
        date: '2026-06-13',
    },
    {
        id: 'dobbeltravern-nordmarkstraveren',
        name: 'Dobbeltravern - Nordmarkstraveren',
        files: ['race-calendar/Nordmakstravern/dobbeltravern_60km_1_.gpx'],
        gpxUpdated: '2026-01-30',
        color: '#f39c12',
        url: 'http://www.nordmarkstravern.no/',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-09-05'
    },
    {
        id: 'lillomarka-rundt',
        name: 'Lillomarka Rundt',
        files: ['race-calendar/Sidespor-SkyBlazers/Lillomarka_rundt_51_km_Frysja_161025.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#1abc9c',
        url: 'https://www.sidespor.no/lop/lillomarka-rundt',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-10-25'
    },
    {
        id: 'flyktningeruta',
        name: 'Flyktningeruta',
        files: ['race-calendar/ØstmarkaTrailChallenge/Flyktningeruta_2025.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#e67e22',
        url: 'https://www.ostmarkatrail.no/flyktningeruta/',
        useCalculatedStats: true,
        category: 'marathon-trail',
        date: '2026-08-26'
    },
    {
        id: 'endless-shore-ultra',
        name: 'Endless Shore Ultra',
        files: ['race-calendar/EndlessShores/Endless_Shores_Ultra_Trail_100M_2026.gpx'],
        gpxUpdated: '2026-05-18',
        color: '#16a085',
        url: 'https://www.endless-shore.no/',
        useCalculatedStats: true,
        category: '100-miles',
        date: '2026-05-23',
        gpxYear: 2026,
    },
    {
        id: 'endless-shore-ultra-50-miles',
        name: 'Endless Shore Ultra 50 Miles',
        files: ['race-calendar/EndlessShores/Endless_Shores_Ultra_trail_50M_2026.gpx'],
        gpxUpdated: '2026-05-18',
        color: '#0e6655',
        url: 'https://www.endless-shore.no/',
        useCalculatedStats: true,
        category: '50-miles',
        date: '2026-05-23',
        gpxYear: 2026,
    },
    {
        id: 'endless-shore-ultra-50k',
        name: 'Endless Shore Ultra 50K',
        files: ['race-calendar/EndlessShores/Endless_Shores_Ultra_Trail_50KM_2026.gpx'],
        gpxUpdated: '2026-05-18',
        color: '#1abc9c',
        url: 'https://www.endless-shore.no/',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-05-23',
        gpxYear: 2026,
    },
    {
        id: 'sandnes-100-miles',
        name: 'Sandnes 100 Miles',
        files: ['race-calendar/SandsnesUltraTrail/sandnes100-miles.gpx'],
        gpxUpdated: '2026-01-30',
        color: '#c0392b',
        url: 'https://www.sandnes100miles.no/',
        useCalculatedStats: true,
        category: '100-miles',
        date: '2026-04-17'
    },
    {
        id: 'lofoten-ultra-trail-100-miles',
        name: 'Lofoten Ultra Trail 100 Miles',
        files: ['race-calendar/LofotenUltraTrail/lofoten-ultra-trail-100-miles.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#2980b9',
        url: 'https://thearctictriple.no/lofoten-ultra-trail-100-miles',
        useCalculatedStats: true,
        category: '100-miles',
        date: '2026-05-28',
    },
    {
        id: 'lofoten-ultra-trail-50-miles',
        name: 'Lofoten Ultra Trail 50 Miles',
        files: ['race-calendar/LofotenUltraTrail/lofoten-ultra-trail-50-miles.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#5dade2',
        url: 'https://thearctictriple.no/lofoten-ultra-trail-50-miles',
        useCalculatedStats: true,
        category: '50-miles',
        date: '2026-05-28',
    },
    {
        id: 'lofoten-ultra-trail-48k',
        name: 'Lofoten Ultra Trail 48K',
        files: ['race-calendar/LofotenUltraTrail/lofoten-ultra-trail-48km.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#85c1e9',
        url: 'https://thearctictriple.no/lofoten-ultra-trail-48-km',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-05-28',
    },
    {
        id: 'mmc-100-miles',
        name: 'MMC 100 Miles',
        files: ['race-calendar/MeråkerMountainChallenge/MMC_100M.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#8e44ad',
        url: 'https://mmctrail.no/100m',
        useCalculatedStats: true,
        category: '100-miles',
        date: '2026-08-01'
    },
    {
        id: 'mmc-100k',
        name: 'MMC 100K',
        files: ['race-calendar/MeråkerMountainChallenge/MMC_100K.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#a569bd',
        url: 'https://mmctrail.no/100k',
        useCalculatedStats: true,
        category: '100k',
        date: '2026-08-01'
    },
    {
        id: 'mmc-70k',
        name: 'MMC 70K',
        files: ['race-calendar/MeråkerMountainChallenge/MMC_70K.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#bb8fce',
        url: 'https://mmctrail.no/70k',
        useCalculatedStats: true,
        category: '50-miles',
        date: '2026-08-01'
    },
    {
        id: 'hardangerjoekulen-ultra-95k',
        name: 'Hardangerjøkulen Ultra 95K',
        files: ['race-calendar/HardangerjøkulenUltra/hardangerjokulen-ultra-95k.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#27ae60',
        url: 'https://xtremeidfjord.no/hardangerjokulen-ultra/',
        useCalculatedStats: true,
        category: '100k',
        date: '2026-07-11'
    },
    {
        id: 'hardangerjoekulen-ultra-34k',
        name: 'Hardangerjøkulen Ultra 34K',
        files: ['race-calendar/HardangerjøkulenUltra/hardangerjokulen-ultra-34k.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#58d68d',
        url: 'https://xtremeidfjord.no/hardangerjokulen-ultra/',
        useCalculatedStats: true,
        category: 'marathon-trail',
        date: '2026-07-11'
    },
    {
        id: 'oslo-trail-challenge-200k',
        name: 'Oslo Trail Challenge 200K',
        files: [
            'race-calendar/OsloTrailChallenge/OTC_200K_First_Half.gpx',
            'race-calendar/OsloTrailChallenge/OTC_100K.gpx'
        ],
        gpxUpdated: '2026-02-02',
        color: '#d35400',
        url: 'https://langtoglenge.org/en/events_en/otc_en.html',
        useCalculatedStats: true,
        category: '100-miles-plus',
        date: '2026-09-20'
    },
    {
        id: 'oslo-trail-challenge-100k',
        name: 'Oslo Trail Challenge 100K',
        files: ['race-calendar/OsloTrailChallenge/OTC_100K.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#dc7633',
        url: 'https://langtoglenge.org/en/events_en/otc_en.html',
        useCalculatedStats: true,
        category: '100k',
        date: '2026-09-27'
    },
    {
        id: 'oslo-trail-challenge-55k',
        name: 'Oslo Trail Challenge 55K',
        files: ['race-calendar/OsloTrailChallenge/OTC_2024_55K_FINAL.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#f0b27a',
        url: 'https://langtoglenge.org/en/events_en/otc_en.html',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-09-27'
    },
    {
        id: 'lustrafjorden-inn-ultra-100',
        name: 'Lustrafjorden Inn Ultra 100',
        files: ['race-calendar/LustrafjordenInn/Lustrafjorden_Inn_2024_Ultra100.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#1a5276',
        url: 'https://www.lustrafjordeninn.no/',
        useCalculatedStats: true,
        category: '100k',
        date: '2026-08-14',
    },
    {
        id: 'hornindal-rundt-75k',
        name: 'Hornindal Rundt 75K',
        files: ['race-calendar/HornindalRundt/HornindalRundt75K.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#7d3c98',
        url: 'https://hornindalrundt.no/',
        useCalculatedStats: true,
        category: '50-miles',
        date: '2026-07-04'
    },
    {
        id: 'dynafit-hardangervidda-maraton-43k',
        name: 'Dynafit Hardangervidda Maraton 43K',
        files: ['race-calendar/HardangerviddaMaraton/hardangervidda-marathon-43k.gpx'],
        gpxUpdated: '2026-02-02',
        color: '#d4ac0d',
        url: 'https://xtremeidfjord.no/hardangerjokulen-ultra/',
        useCalculatedStats: true,
        category: 'marathon-trail',
        date: '2026-08-29'
    },
    {
        id: 'noesen-50k',
        name: 'Nøsen 50K',
        files: ['race-calendar/Nøsen/Nosen_50km.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#cb4335',
        url: 'https://www.nosenhundreds.com/50km',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-06-14',
    },
    {
        id: 'krsultra-60',
        name: 'KRSUltra 60',
        files: ['race-calendar/KRSUltra/krsultra-60k-2025-v1.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#e55039',
        url: 'https://www.krsultra.no/lop/krsultra-60',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-04-11',
        gpxYear: 2025,
    },
    {
        id: 'skogvokteren',
        name: 'Skogvokteren',
        files: ['race-calendar/Skogvokteren/Skogvokteren_2025.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#2d6a4f',
        url: 'https://grenlandultrarunners.no/skogvokteren-ultra-2/',
        useCalculatedStats: true,
        category: '50-miles',
        date: '2026-05-02',
        gpxYear: 2025,
    },
    {
        id: 'ecotrail-oslo-80k',
        name: 'Ecotrail Oslo 80K',
        files: ['race-calendar/ecotrail/ecotrail_oslo_80km_2026.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#40916c',
        url: 'https://oslo.ecotrail.com/en/race-ecotrail-oslo/trail-80-km',
        useCalculatedStats: true,
        category: '50-miles',
        date: '2026-05-30',
    },
    {
        id: 'ecotrail-oslo-50k',
        name: 'Ecotrail Oslo 50K',
        files: ['race-calendar/ecotrail/ecotrail_oslo_50km_2026.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#74c69d',
        url: 'https://oslo.ecotrail.com/en/race-ecotrail-oslo/trail-80-km',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-05-30'
    },
    {
        id: 'sognefjord-trail-run-50k',
        name: 'Sognefjord Trail Run 50K',
        files: ['race-calendar/SognefjordTrail/STR+50K+2026.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#0077b6',
        url: 'https://www.sognefjordtrailrun.com/50k',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-06-06'
    },
    {
        id: 'vestfold-historic-ultra-147k',
        name: 'Vestfold Historic Ultra 147K',
        files: ['race-calendar/VestfoldHistoricUltra/VHUT_2025_147km.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#6930c3',
        url: 'https://www.vhut.no/loyper/',
        useCalculatedStats: true,
        category: '100-miles',
        date: '2026-06-06'
    },
    {
        id: 'vestfold-historic-ultra-87k',
        name: 'Vestfold Historic Ultra 87K',
        files: ['race-calendar/VestfoldHistoricUltra/VHUT_2025_87km.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#7400b8',
        url: 'https://www.vhut.no/loyper/',
        useCalculatedStats: true,
        category: '50-miles',
        date: '2026-06-06'
    },
    {
        id: 'vestfold-historic-ultra-50k',
        name: 'Vestfold Historic Ultra 50K',
        files: ['race-calendar/VestfoldHistoricUltra/VHUT_2025_50km.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#9d4edd',
        url: 'https://www.vhut.no/loyper/',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-06-07'
    },
    {
        id: 'jotunheimen-trail-run',
        name: 'Jotunheimen Trail Run',
        files: ['race-calendar/JotunheimenTrail/JTR+ULTRA+2026.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#023e8a',
        url: 'https://www.jotunheimentrailrun.com/',
        useCalculatedStats: true,
        category: '50-miles',
        date: '2026-07-31'
    },
    {
        id: 'bodoeryggen-ultra',
        name: 'Bodøryggen Ultra',
        files: ['race-calendar/Bodoryggen/Bodoryggen_2025_ultra.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#00b4d8',
        url: 'https://bodorunfestival.no/bodoryggen/',
        useCalculatedStats: true,
        category: 'marathon-trail',
        date: '2026-08-01'
    },
    {
        id: 'stranda-fjord-trail-55k',
        name: 'Stranda Fjord Trail 55K',
        files: ['race-calendar/StrandaFjordTrail/55k.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#ff6d00',
        url: 'https://strandafjordtrailrace.com/',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-08-12'
    },
    {
        id: 'stranda-fjord-trail-95k',
        name: 'Stranda Fjord Trail 95K',
        files: ['race-calendar/StrandaFjordTrail/95K.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#ff9500',
        url: 'https://strandafjordtrailrace.com/',
        useCalculatedStats: true,
        category: '100k',
        date: '2026-08-12'
    },
    {
        id: 'trollheimen-ultra-100k',
        name: 'Trollheimen Ultra 100K',
        files: ['race-calendar/TrollheimenUltra/trollheimen-ultra-trip.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#6a040f',
        url: 'https://trollheimenultra100km.webnode.page/',
        useCalculatedStats: true,
        category: '100k',
        date: '2026-08-15'
    },
    {
        id: 'tromsoe-mountain-challenge-50k',
        name: 'Tromsø Mountain Challenge 50K',
        files: ['race-calendar/TromsoMountainChallenge/TMC_Ultra_50km_2025.gpx'],
        gpxUpdated: '2026-02-17',
        color: '#4cc9f0',
        url: 'https://msm.no/en/mountain-challenge/loypekart-tromso-mountain-challenge/',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-08-22'
    },
    {
        id: 'blefjell-troll-57k',
        name: 'Blefjell Troll 57K',
        files: ['race-calendar/Blefjell/BB_01_Troll_4.gpx'],
        gpxUpdated: '2026-02-18',
        color: '#5c4033',
        url: 'https://blefjellsbeste.com/',
        useCalculatedStats: true,
        category: '50k',
        date: '2026-07-24'
    },
    {
        id: 'blefjell-storetroll-96k',
        name: 'Blefjell Storetroll 96K',
        files: [
            'race-calendar/Blefjell/BB_01_Troll_4.gpx',
            'race-calendar/Blefjell/BB_02_Tusser_3.gpx',
            'race-calendar/Blefjell/BB_10K_Smatusser.gpx',
            'race-calendar/Blefjell/BB_05K_Smatroll.gpx'
        ],
        gpxUpdated: '2026-02-18',
        color: '#3d2817',
        url: 'https://blefjellsbeste.com/',
        useCalculatedStats: true,
        category: '100k',
        date: '2026-07-24'
    }
];
